#include "i2s.h"
#include "i2s_tx.pio.h"       // generated by pico_generate_pio_header()
#include "config.h"
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/clocks.h"
#include <string.h>

// ---------------------------------------------------------------------------
// Module state
// ---------------------------------------------------------------------------
static PIO  _pio       = pio0;
static uint _sm        = 0;
static uint _pio_offset = 0;

static int  _dma_ch_a  = -1;
static int  _dma_ch_b  = -1;

static i2s_buffers_t    _bufs;
static volatile uint8_t _front = 0;   // buffer index currently being played

static i2s_fill_callback_t _fill_cb = NULL;

// ---------------------------------------------------------------------------
// DMA IRQ handler
// Fires when the playing buffer finishes. Restarts DMA on the other buffer,
// then calls the fill callback so the audio engine can refill the old one.
// ---------------------------------------------------------------------------
static void _dma_irq_handler(void) {
    int  done_ch  = dma_hw->ints0 & (1u << _dma_ch_a) ? _dma_ch_a : _dma_ch_b;
    uint done_buf = (done_ch == _dma_ch_a) ? 0 : 1;

    // Clear IRQ flag
    dma_hw->ints0 = (1u << done_ch);

    // Refill the buffer that just finished
    if (_fill_cb)
        _fill_cb(_bufs.buf[done_buf], I2S_BUF_WORDS);

    // Point completed channel back to the refilled buffer
    // start=false — the other channel's chain_to will trigger it at the right time
    dma_channel_set_read_addr(done_ch, _bufs.buf[done_buf], false);
}

// ---------------------------------------------------------------------------
// i2s_init
// ---------------------------------------------------------------------------
void i2s_init(void) {
    // Zero buffers (produces silence at startup)
    memset(&_bufs, 0, sizeof(_bufs));

    // ---- PIO setup ---------------------------------------------------------
    _pio_offset = pio_add_program(_pio, &i2s_tx_program);

    pio_sm_config cfg = i2s_tx_program_get_default_config(_pio_offset);

    // OUT pin  = DATA
    sm_config_set_out_pins(&cfg, PIN_I2S_DATA, 1);

    // SIDE-SET base = BCK; next consecutive pin = LRCK
    // side-set bit 0 = BCK (PIN_I2S_BCK), bit 1 = LRCK (PIN_I2S_LRCK)
    sm_config_set_sideset_pins(&cfg, PIN_I2S_BCK);

    // Shift OSR right (MSB first), autopull at 32 bits
    sm_config_set_out_shift(&cfg, false, true, 32);   // shift_right=false → MSB first
    // NOTE: RP2040 "shift right" in PIO shifts toward LSB, so OSR bit31 comes
    //       out first when shift_direction=false (left shift = MSB first).
    //       double-check against SDK docs if samples appear byte-reversed.

    // PIO clock divider: SYS_CLK / (BCK_freq * 2)
    // BCK_freq = SAMPLE_RATE * 64 (32-bit stereo frames)
    float pio_clk  = (float)AUDIO_SAMPLE_RATE * 64.0f * 2.0f;
    float sys_clk  = (float)clock_get_hz(clk_sys);
    float div      = sys_clk / pio_clk;
    sm_config_set_clkdiv(&cfg, div);

    // Initialise GPIO directions before handing to PIO
    pio_gpio_init(_pio, PIN_I2S_DATA);
    pio_gpio_init(_pio, PIN_I2S_BCK);
    pio_gpio_init(_pio, PIN_I2S_LRCK);

    pio_sm_set_consecutive_pindirs(_pio, _sm, PIN_I2S_DATA, 1,  true);  // DATA out
    pio_sm_set_consecutive_pindirs(_pio, _sm, PIN_I2S_BCK,  2,  true);  // BCK, LRCK out

    pio_sm_init(_pio, _sm, _pio_offset + i2s_tx_offset_entry_point, &cfg);

    // ---- DMA setup ---------------------------------------------------------
    _dma_ch_a = dma_claim_unused_channel(true);
    _dma_ch_b = dma_claim_unused_channel(true);

    // Both channels have identical config; they chain to each other
    dma_channel_config da = dma_channel_get_default_config(_dma_ch_a);
    channel_config_set_transfer_data_size(&da, DMA_SIZE_32);
    channel_config_set_read_increment(&da, true);
    channel_config_set_write_increment(&da, false);
    channel_config_set_dreq(&da, pio_get_dreq(_pio, _sm, true));
    channel_config_set_chain_to(&da, _dma_ch_b);   // A → B → A ping-pong
    channel_config_set_irq_quiet(&da, false);

    dma_channel_configure(_dma_ch_a, &da,
        &_pio->txf[_sm],          // write to PIO TX FIFO
        _bufs.buf[0],             // read from buffer 0
        I2S_BUF_WORDS,
        false);                   // don't start yet

    dma_channel_config db = dma_channel_get_default_config(_dma_ch_b);
    channel_config_set_transfer_data_size(&db, DMA_SIZE_32);
    channel_config_set_read_increment(&db, true);
    channel_config_set_write_increment(&db, false);
    channel_config_set_dreq(&db, pio_get_dreq(_pio, _sm, true));
    channel_config_set_chain_to(&db, _dma_ch_a);   // B → A
    channel_config_set_irq_quiet(&db, false);

    dma_channel_configure(_dma_ch_b, &db,
        &_pio->txf[_sm],
        _bufs.buf[1],
        I2S_BUF_WORDS,
        false);

    // IRQ on DMA channel A and B completion
    dma_channel_set_irq0_enabled(_dma_ch_a, true);
    dma_channel_set_irq0_enabled(_dma_ch_b, true);

    irq_set_exclusive_handler(DMA_IRQ_0, _dma_irq_handler);
    irq_set_enabled(DMA_IRQ_0, true);
}

void i2s_set_fill_callback(i2s_fill_callback_t cb) {
    _fill_cb = cb;
}

void i2s_start(void) {
    pio_sm_set_enabled(_pio, _sm, true);
    dma_channel_start(_dma_ch_a);   // starts A; A chains to B; B chains to A
}

void i2s_stop(void) {
    dma_channel_abort(_dma_ch_a);
    dma_channel_abort(_dma_ch_b);
    pio_sm_set_enabled(_pio, _sm, false);
}
